/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'pouncilt' at '11/7/13 11:10 AM' with Gradle 1.8
 *
 * @author pouncilt, @date 11/7/13 11:10 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
